# The only theme that I made myself
# because this one was kinda dead easy

cursor     #1AFF1A
cursor_text_color #000000
selection_foreground #000000
selection_background #1AFF1A
foreground #1AFF1A
background #000000
color0     #000000
color8     #000000
color1     #1AFF1A
color9     #1AFF1A
color2     #1AFF1A
color10    #1AFF1A
color3     #1AFF1A
color11    #1AFF1A
color4     #1AFF1A
color12    #1AFF1A
color5     #1AFF1A
color13    #1AFF1A
color6     #1AFF1A
color14    #1AFF1A
color7     #1AFF1A
color15    #1AFF1A
